### PR TITLE
Fix compatibility issues with python3

### PR DESCRIPTION
**Pull request by guozijn**
Signed-off-by: guozijian <guozijian@unitedstack.com>

### CODE REVIEW

**Comment by guozijn** [comment]
#1

**Comment by dhellmann** [comment]
Now that python 2 is no longer supported I think it's safe to rewrite this using the python 3 style and without using six.

**Comment by dhellmann** [comment]
Thanks!

**Comment by dhellmann** [comment]
I published this change in version 0.1.2.

**Pull request merged**
